### ISSUE TITLE
Unable to share data between states

### ISSUE THREAD

**Issue by BayoKwendo** [harmonizerblinks/ussd-builder#1]
Is there a way we can pass data between states?

**Comment by BayoKwendo** [comment]
I have come to conclusion that Redis can do this job perfectly.

**Comment by harmonizerblinks** [comment]
> 

yes, you save the data in session and when the user gets to the next state u can get the value from the session. 

here is a link to a sample USSD Application developed using this plugin

**Comment by damianochintala** [comment]
> 

@harmonizerblinks are you able to share the link the application were data was being shared across states?
