### ISSUE TITLE
End State not being executed gracefully

### ISSUE THREAD

**Issue by damianochintala** [harmonizerblinks/ussd-builder#3]
When ever the en state is called, it gets executed but then my app crashes with error:

`Failed to get route: TypeError: Cannot read properties of undefined (reading 'split')
    at UssdMenu.resolveRoute (E:\Dev\ussd\node_modules\ussd-builder\lib\ussd-menu.js:135:47)`

Here is my code snippet for the states where the 'end' state is being called:

`menu.state('handleOptions', {
  run: async () => {
    const option = menu.val.trim();
    const phoneNumber = menu.args.phoneNumber;

    const farmer = await getFarmerByPhoneNumber(phoneNumber);
    if (!farmer) {
      // User is new
      menu.session.set('name', option);
      menu.end(`Hello, ${option}! Your name has been saved.`);
    } else {
      switch (option) {
        case '1':
          // Fetch Weather

            // Display weather information
            menu.con(
              `Weather Data for ${weatherData.name}:\n` +
              `Description: ${weatherData.weather[0].description}\n` +
              `Temperature: ${weatherData.main.temp}°C\n` +
              `Humidity: ${weatherData.main.humidity}%\n` +
              '1. Go back to main menu\n' +
              '2. Quit'
            );
          } catch (error) {
            menu.con('Failed to fetch weather data.');
          }
          break;
        case '2':
          const agentName = farmer.agent_name;
          menu.con(`Your agent's name is ${agentName}.\n` +
            '1. Go back to main menu\n' +
            '2. Quit');
          break;
        case '3':
          const loanBalance = farmer.loan_balance;
          menu.con(`Your loan balance is K${loanBalance}.\n` +
            '1. Go back to main menu\n' +
            '2. Quit');
          break;
        default:
          menu.con('Invalid option. Please select again:');
          break;
      }
    }
  },
  next: {
    '1': 'mainMenu',
    '2': 'end',
    '*': 'handleOptions',
  },
});

menu.state('end', {
  run: () => {
    menu.end('Thank you for using our services. Goodbye!');
  },
});
`

**Comment by harmonizerblinks** [comment]
Resolved
