### ISSUE TITLE
Menu StartState regex as next state

### ISSUE THREAD

**Issue by japhethkiptoo** [harmonizerblinks/ussd-builder#4]
I have this menu i want to ask for PIN on __start__ because the next state will perform login validation.
It is working as expected but after successful login and getting a menu of 1,2,3,4 and i select 1 somehow it is being caught by startstate regex.

i cant proceed to other states, i am blocked

**Comment by harmonizerblinks** [comment]
menu.startState({
    run: () => {
        menu.con('Enter your PIN to continue');
    },
    next: {
        '*\\d+': 'MainMenu'
    }
})

menu.state('MainMenu',{
    run: async() => {
        var payload = { mobile: menu.args.phoneNumber, pin:  menu.val }
        await validateCustomer(payload, (data)=> {
            if(data && data.active && data.valid ) {
                menu.session.set('cust', data);

                menu.con('Welcome to Main Menu.' + 
                '\nSelect an Option.' + 
                '\n1. Deposit' +
                '\n2. Withdrawal' +
                '\n3. Check Balance' +
                '\n4. Other' +
                '\n5. Contact');

            } else {
                menu.end('Mobile Number not Registered, kindly Open an Account.');
            }
        }).catch((err)=>{ menu.end(err); });
    },
    // next object links to next state based on user input
    next: {
        '1': 'Deposit',
        '2': 'Withdrawal',
        '3': 'CheckBalance',
        '4': 'Other',
        '5': 'Contact',
        '*[0-9]+': 'User.newpin'
    }
});

**Comment by harmonizerblinks** [comment]
```javascript
menu.startState({
    run: () => {
        menu.con('Enter your PIN to continue');
    },
    next: {
        '*\d+': 'MainMenu'
    }
});

menu.state('MainMenu', {
    run: async () => {
        var payload = { mobile: menu.args.phoneNumber, pin: menu.val }
        await validateCustomer(payload, (data) => {
            if (data && data.active && data.valid) {
                menu.session.set('cust', data);
                menu.con('Welcome to Main Menu.' +
                    '\nSelect an Option.' +
                    '\n1. Deposit' +
                    '\n2. Withdrawal' +
                    '\n3. Check Balance' +
                    '\n4. Other' +
                    '\n5. Contact');
            } else {
                menu.end('Mobile Number not Registered, kindly Open an Account.');
            }
        }).catch((err) => { menu.end(err); });
    },
    next: {
        '1': 'Deposit',
        '2': 'Withdrawal',
        '3': 'CheckBalance',
        '4': 'Other',
        '5': 'Contact',
        '*[0-9]+': 'User.newpin'
    }

});

```
