### ISSUE TITLE
Regex for phone numbers, time and Dates

### ISSUE THREAD

**Issue by Ortiz25** [harmonizerblinks/ussd-builder#7]
I have tried a number of regex for Date, Time and Phone Number validations but none seem to work but they work with other libraries, any idea of which ones work with uss-builder??

**Comment by harmonizerblinks** [comment]
You can accept the value and validate it using other libraries. The ussd-builder isn't supposed to validate data; it only helps you accept the type of data you specified. This can be done using the [pattern](https://www.w3schools.com/tags/att_input_pattern.asp) attribute. If you want more advanced validation, you would have to use other libraries.
