### ISSUE TITLE
Allow For Regex Options

### ISSUE THREAD

**Issue by nigelnindodev** [harmonizerblinks/ussd-builder#8]
**_Motivation:_**
To give an example of motivation for this issue, I may ask a user what country they are from. There are too many countries in the world to fit into USSD options, so I'd like them to enter their country of origin as a string, and verify it's correct regardless of case used in their input.

**_Issue:_**
As shown in the [code snippet](https://github.com/harmonizerblinks/ussd-builder/blob/9d15df6b2913a77761dcebc409dca01587c3c6f1/lib/ussd-menu.js#L155), the library currently doesn't allow for passing in of regex options when validating if `val` is valid or not.

Currently, JavaScript Regex does not allow for inline modifiers in the passed-in string: https://stackoverflow.com/a/37208514/22694455

An example use case is to define a list of optional values and make them case-insensitive:

```javascript
...
next: {
  [`*/^(KENYA|TANZANIA|UGANDA)$/i`]: 'getDetails.city'
}
...
```
The default JavaScript implementation will ignore the `/i` flag in the Regex. So the library will only accept `KENYA` as valid input and reject `Kenya` or `kenya`.

There are workarounds, but the simplest way around this might be [to allow options in RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/ignoreCase)

**Comment by nigelnindodev** [comment]
Also posting the workaround to add case insensitivity options in the regex, just in case anyone else might be interested:

```typescript
function toCaseInsensitivePattern(pattern: string): string {
	return pattern.replace(/[a-z]/gi, (c: string) => {
		return `[${c.toUpperCase()}${c.toLowerCase()}]`;
	});
}

const rule: string = '^(KENYA|TANZANIA|UGANDA)$';
const caseInsensitiveRule: string = toCaseInsensitivePattern(rule);

console.log('Case-insensitive Rule: ', caseInsensitiveRule);

const re: RegExp = new RegExp(caseInsensitiveRule);

console.log(re.test('keny')); // outputs false
console.log(re.test('KenYa')); // outputs true
console.log(re.test('kenya')); // outputs true
console.log(re.test('KENYA')); // outputs true

```

**Comment by harmonizerblinks** [comment]
it's advisable you handle validation like this in the function level after receiving the value, so you can return the right error message to your users / customers.

**Comment by nigelnindodev** [comment]
That's also another solution, but one I wanted to avoid, because it requires a new intermediary state for the validation.

Fair enough, I will use the workaround posted on this issue.
